//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Tranzactions = new HashSet<Tranzaction>();
            this.Tranzactions1 = new HashSet<Tranzaction>();
        }
    
        public int Id { get; set; }
        public string IBAN { get; set; }
        public int ID_Client { get; set; }
        public int ID_Offer { get; set; }
        public string Currency { get; set; }
        public decimal Total { get; set; }
    
        public virtual AccountOffer AccountOffer { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tranzaction> Tranzactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tranzaction> Tranzactions1 { get; set; }
    }
}
