//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanProfile
    {
        public long id { get; set; }
        public string name { get; set; }
        public long id_batch_schema { get; set; }
        public long id_workflow { get; set; }
        public string scanner_name { get; set; }
        public string resolution { get; set; }
        public string color_depth { get; set; }
        public string scan_source { get; set; }
        public string paper_size { get; set; }
        public string cropping { get; set; }
        public string brightness { get; set; }
        public string contrast { get; set; }
        public long bit_settings { get; set; }
        public string scanner_settings { get; set; }
        public string DRIVER_ID { get; set; }
        public string name_rescan { get; set; }
        public Nullable<bool> for_scan { get; set; }
        public Nullable<bool> for_rescan { get; set; }
        public Nullable<bool> auto_crop { get; set; }
    }
}
