//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tranzaction
    {
        public int Id { get; set; }
        public int Id_SourceAccount { get; set; }
        public int ID_DestinationAccount { get; set; }
        public string Source_Currency { get; set; }
        public string Destination_Currency { get; set; }
        public decimal Ammount { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
    }
}
